apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: pavanhgowda/story-node-app
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/story
              name: story-volume       
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc



