apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: pavan
spec:
  selector:
    app: second-app
  ports: 
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer